<a href="https://colab.research.google.com/github/MonikaLamba/DEEPLEARNING/blob/master/10886_complete_grade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/10886_complete')


Mounted at /content/10886_complete


In [3]:
mydata_10886_c_grade = pd.read_csv('/content/10886_complete/MyDrive/10886_complete_grade.csv')
mydata_10886_c_grade.head()

SCN4A  13CDNA73       VCL        FS  ...  I_1100357     HBXAP    MAP4K4  GRADE
0  0.547133  0.632416  0.626759  0.500672  ...   0.700940  0.500389  0.560427      3
1  0.485898  0.655476  0.522190  0.492913  ...   0.533357  0.468432  0.411811      3
2  0.455341  0.594054  0.489674  0.423112  ...   0.517298  0.439819  0.391147      3
3  0.466215  0.585794  0.487378  0.485372  ...   0.472647  0.434332  0.463863      3
4  0.441978  0.590871  0.453596  0.458852  ...   0.497925  0.446266  0.328354      2

[5 rows x 16381 columns]

In [5]:
print(mydata_10886_c_grade.keys())

Index(['SCN4A', '13CDNA73', 'VCL', 'FS', 'I_1000682', 'AMSH', 'PRKCL2',
       'I_1100727', 'NM_014294.2', 'NM_020150.3',
       ...
       'FLJ13659', 'DIRC2', 'I_1109479', 'MYF6', 'I_965593', 'SLC12A6',
       'I_1100357', 'HBXAP', 'MAP4K4', 'GRADE'],
      dtype='object', length=16381)


In [6]:
X=mydata_10886_c_grade.drop(["GRADE"],axis=1)
y=mydata_10886_c_grade["GRADE"]  
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0) 
print(X_train)
print(X_test)
print(y_train) 
print(y_test) 


       SCN4A  13CDNA73       VCL  ...  I_1100357     HBXAP    MAP4K4
66  0.526310  0.588947  0.553830  ...   0.549609  0.492149  0.450785
27  0.478348  0.648072  0.550106  ...   0.532123  0.410849  0.400319
48  0.505895  0.540442  0.519620  ...   0.578685  0.463312  0.443956
57  0.417555  0.755222  0.423298  ...   0.564965  0.448665  0.312425
53  0.478902  0.706013  0.482694  ...   0.590140  0.478180  0.372178
6   0.556912  0.669639  0.606822  ...   0.680983  0.531096  0.475632
49  0.492444  0.666009  0.506767  ...   0.486692  0.483535  0.468817
69  0.535936  0.683016  0.540776  ...   0.662481  0.477863  0.413773
4   0.441978  0.590871  0.453596  ...   0.497925  0.446266  0.328354
55  0.494150  0.624182  0.476529  ...   0.567489  0.469982  0.415169
59  0.550723  0.681143  0.546995  ...   0.560141  0.466675  0.445876
2   0.455341  0.594054  0.489674  ...   0.517298  0.439819  0.391147
73  0.472026  0.620055  0.480536  ...   0.487839  0.443704  0.392964
45  0.444359  0.718770  0.448605  

In [7]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler() 
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
X_train 

array([[ 1.06139216, -0.85158976,  0.93694356, ..., -0.01419548,
         0.88061618,  0.48458345],
       [-0.20576781,  0.14550526,  0.86413904, ..., -0.30806423,
        -1.42223899, -0.48334339],
       [ 0.52201905, -1.66958897,  0.26799534, ...,  0.47444746,
         0.06377656,  0.35359602],
       ...,
       [ 0.12473432,  0.24218002, -0.31360389, ..., -0.06709297,
        -0.45158337, -0.72599831],
       [-0.36520641, -0.07025697, -0.96940967, ..., -1.30078611,
        -1.37707964, -0.74127321],
       [ 0.80789993,  1.07926291,  0.055495  , ...,  0.2481593 ,
         0.76037441,  0.63576928]])

In [8]:
from sklearn.svm import SVC
classifier=SVC() 
classifier.fit(X_train,y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [10]:
y_pred=classifier.predict(X_test)
y_pred 
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm)
print(accuracy_score(y_pred,y_test) )
classification_report(y_pred,y_test)

[[0 0 0]
 [0 1 0]
 [2 3 9]]
0.6666666666666666


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n           1       0.00      0.00      0.00         0\n           2       0.25      1.00      0.40         1\n           3       1.00      0.64      0.78        14\n\n    accuracy                           0.67        15\n   macro avg       0.42      0.55      0.39        15\nweighted avg       0.95      0.67      0.76        15\n'

In [11]:
from  sklearn.linear_model import LogisticRegression 
lg_classifier=LogisticRegression(random_state=0)
lg_classifier.fit(X_train,y_train) 

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
y_pred=lg_classifier.predict(X_test)
y_pred 

array([2, 3, 2, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2])

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm) 
accuracy_score(y_pred,y_test) 
classification_report(y_pred,y_test)

[[0 0 0]
 [2 3 1]
 [0 1 8]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n           1       0.00      0.00      0.00         0\n           2       0.75      0.50      0.60         6\n           3       0.89      0.89      0.89         9\n\n    accuracy                           0.73        15\n   macro avg       0.55      0.46      0.50        15\nweighted avg       0.83      0.73      0.77        15\n'

In [15]:
from sklearn.neighbors import KNeighborsClassifier
KN_classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2) 
KN_classifier.fit(X_train,y_train) 
y_pred=KN_classifier.predict(X_test)
y_pred 
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm) 
accuracy_score(y_pred,y_test) 
classification_report(y_pred,y_test)

[[0 1 0]
 [1 2 2]
 [1 1 7]]


'              precision    recall  f1-score   support\n\n           1       0.00      0.00      0.00         1\n           2       0.50      0.40      0.44         5\n           3       0.78      0.78      0.78         9\n\n    accuracy                           0.60        15\n   macro avg       0.43      0.39      0.41        15\nweighted avg       0.63      0.60      0.61        15\n'

In [16]:
from sklearn.naive_bayes import GaussianNB 
NB_classifier=GaussianNB()
NB_classifier.fit(X_train,y_train)
y_pred=NB_classifier.predict(X_test) 
y_pred  
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm) 
accuracy_score(y_pred,y_test) 
classification_report(y_pred,y_test)

[[1 1 1]
 [1 1 1]
 [0 2 7]]


'              precision    recall  f1-score   support\n\n           1       0.50      0.33      0.40         3\n           2       0.25      0.33      0.29         3\n           3       0.78      0.78      0.78         9\n\n    accuracy                           0.60        15\n   macro avg       0.51      0.48      0.49        15\nweighted avg       0.62      0.60      0.60        15\n'

In [17]:
from sklearn.tree import DecisionTreeClassifier
D_classifier=DecisionTreeClassifier(criterion="entropy",random_state=0) 
D_classifier.fit(X_train,y_train) 
y_pred =D_classifier.predict(X_test)
y_pred 
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm) 
accuracy_score(y_pred,y_test) 
classification_report(y_pred,y_test)

[[0 1 1]
 [2 1 1]
 [0 2 7]]


'              precision    recall  f1-score   support\n\n           1       0.00      0.00      0.00         2\n           2       0.25      0.25      0.25         4\n           3       0.78      0.78      0.78         9\n\n    accuracy                           0.53        15\n   macro avg       0.34      0.34      0.34        15\nweighted avg       0.53      0.53      0.53        15\n'

In [18]:
from sklearn.ensemble import RandomForestClassifier 
rc_classifier=RandomForestClassifier(n_estimators=20,criterion="entropy",random_state=0)
rc_classifier.fit(X_train,y_train) 
y_pred=rc_classifier.predict(X_test)
y_pred
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_pred,y_test) 
print(cm) 
accuracy_score(y_pred,y_test)
classification_report(y_pred,y_test)

[[0 1 1]
 [2 3 1]
 [0 0 7]]


'              precision    recall  f1-score   support\n\n           1       0.00      0.00      0.00         2\n           2       0.75      0.50      0.60         6\n           3       0.78      1.00      0.88         7\n\n    accuracy                           0.67        15\n   macro avg       0.51      0.50      0.49        15\nweighted avg       0.66      0.67      0.65        15\n'

In [20]:
from sklearn.model_selection import cross_val_score 
cross_validation=cross_val_score(estimator=rc_classifier,X=X_train,y=y_train) 
cross_validation
print("cross validation mean accuracy",cross_validation.mean()) 

cross validation mean accuracy 0.7075757575757576
